### ISSUE TITLE
expected "data- n" command, found...

### ISSUE THREAD

**Issue by ratnanil** [c-w/ghp-import#100] opened 2021-08-06 14:30 UTC
I had used ghp-import successfully in windows, but no I swiched to linux an get the following error message when I run `ghp-import docs`:

```
fatal: Expected 'data n' command, found: 
fast-import: dumping crash report to .git/fast_import_crash_85004
Traceback (most recent call last):
  File "/home/nils/.local/bin/ghp-import", line 8, in <module>
    sys.exit(main())
  File "/home/nils/.local/lib/python3.8/site-packages/ghp_import.py", line 278, in main
    ghp_import(args[0], **opts.__dict__)
  File "/home/nils/.local/lib/python3.8/site-packages/ghp_import.py", line 257, in ghp_import
    run_import(git, srcdir, **opts)
  File "/home/nils/.local/lib/python3.8/site-packages/ghp_import.py", line 192, in run_import
    pipe.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
```

I dont even beginn to know how I could debug this, can you give me a hint?

<details>
<summary>Click to expand what the crash report says</summary>
        
          fast-import crash report:
            fast-import process: 85004
            parent process     : 85002
            at 2021-08-06 14:26:18 +0000
        
        fatal: Expected 'data n' command, found: 
        
        Most Recent Commands Before Crash
        ---------------------------------
          M 100644 inline mithelfen-anpacken-mithelfen/19-newsletter-abonnieren/index.html
          data 56612
          M 100644 inline mithelfen-anpacken-mithelfen/22-kontaktformular/index.html
          data 55895
          M 100644 inline mithelfen-anpacken-mithelfen/22-kontaktformular/1391103200_Blog_Artdesigner.lv.png
          data 15270
          M 100644 inline mithelfen-anpacken-mithelfen/75-teamtraining-mit-wiesel-co-am-zimmerb/Team_in_Aktion_WiCoZ.JPG
          data 138359
          M 100644 inline mithelfen-anpacken-mithelfen/75-teamtraining-mit-wiesel-co-am-zimmerb/index.html
          data 59495
          M 100644 inline mithelfen-anpacken-mithelfen/20-anpacken/index.html
          data 59136
          M 100644 inline site_libs/font-awesome-5.1.0/css/all.css
          data 45687
          M 100644 inline site_libs/font-awesome-5.1.0/css/v4-shims.css
          data 41293
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-brands-400.woff
          data 73920
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-brands-400.woff2
          data 63376
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-brands-400.ttf
          data 114816
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-regular-400.woff2
          data 14952
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-solid-900.woff
          data 76632
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-solid-900.woff2
          data 59572
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-regular-400.ttf
          data 40516
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-brands-400.svg
          data 622420
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-regular-400.eot
          data 40744
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-brands-400.eot
          data 115052
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-solid-900.eot
          data 160768
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-solid-900.svg
          data 592839
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-regular-400.svg
          data 141551
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-regular-400.woff
          data 18212
          M 100644 inline site_libs/font-awesome-5.1.0/webfonts/fa-solid-900.ttf
          data 160548
          M 100644 inline site_libs/lightable-0.0.1/lightable.css
          data 5090
          M 100644 inline site_libs/headroom-0.9.4/headroom.min.js
          data 5359
          M 100644 inline site_libs/popper-2.6.0/popper.min.js
          data 18453
          M 100644 inline site_libs/jquery-1.11.3/jquery.min.js
          data 95957
          M 100644 inline site_libs/webcomponents-2.0.0/webcomponents.js
          data 94086
          M 100644 inline site_libs/bowser-1.9.3/bowser.min.js
          data 7496
          M 100644 inline site_libs/tippy-6.2.7/tippy.umd.min.js
          data 22451
          M 100644 inline site_libs/tippy-6.2.7/tippy-light-border.css
          data 2810
          M 100644 inline site_libs/tippy-6.2.7/tippy.css````
          data 1390
          M 100644 inline site_libs/tippy-6.2.7/tippy-bundle.umd.min.js
          data 24077
          M 100644 inline site_libs/distill-2.2.21/template.v2.js
          data 143721
          M 100644 inline site_libs/fuse-6.4.1/fuse.min.js
          data 22858
          M 100644 inline site_libs/autocomplete-0.37.1/autocomplete.min.js
          data 57214
          M 100644 inline site_libs/header-attrs-2.8/header-attrs.js
          data 507
          M 100644 inline site_libs/kePrint-0.0.1/kePrint.js
          data 275
          M 100644 inline site_libs/anchor-4.2.2/anchor.min.js
          data 5827
          M 100644 inline wissenschaft-externe-projekte/wissenschaft-externe-projekte.json
          data 12542
          M 100644 inline wissenschaft-externe-projekte/131-nistkammer-monitoring/schema_Nistkammer-Monit-2.jpg
          data 50295
          M 100644 inline wissenschaft-externe-projekte/131-nistkammer-monitoring/index.html
          data 60240
          M 100644 inline wissenschaft-externe-projekte/131-nistkammer-monitoring/07260411-korr-hochf.jpg
          data 425484
          M 100644 inline wissenschaft-externe-projekte/90-stiftung-wieselnetz-win-wiesel-patchw/WIN_patchwork.png
          data 615619
          M 100644 inline wissenschaft-externe-projekte/90-stiftung-wieselnetz-win-wiesel-patchw/index.html
          data 59355
          M 100644 inline wissenschaft-externe-projekte/89-stiftung-wieselnetz-win-foerdermassna/index.html
          data 59107
          M 100644 inline wissenschaft-externe-projekte/89-stiftung-wieselnetz-win-foerdermassna/WIN_foerdermassnahmen.png
          data 434355
          M 100644 inline wissenschaft-externe-projekte/87-monitoring-der-kleinmusteliden-in-der/CSCF.png
          data 676999
          M 100644 inline wissenschaft-externe-projekte/87-monitoring-der-kleinmusteliden-in-der/index.html
          data 61249
          M 100644 inline wissenschaft-externe-projekte/126-mammaliabox/126-mammaliabox.Rmd
        * 
        
        Active Branch LRU
        -----------------
            active_branches = 1 cur, 5 max
        
          pos  clock name
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           1)      0 refs/heads/gh-pages
        
        Inactive Branches
        -----------------
        refs/heads/gh-pages:
          status      : active loaded dirty
          tip commit  : 75d11ffd69e0a8fcd46d1542dd7ea9e894dfbf6a
          old tree    : 0000000000000000000000000000000000000000
          cur tree    : 0000000000000000000000000000000000000000
          commit clock: 0
          last pack   : 
        
        
        Marks
        -----
        
        -------------------
        END OF CRASH REPORT

</details>

**Comment by c-w** [comment] 2021-08-06 16:33
Thanks for the report. What version of git are you on?

**Comment by ratnanil** [comment] 2021-08-09 07:35
sorry for the late reply!

```
$ git --version
git version 2.25.1
```

**Comment by ratnanil** [comment] 2021-08-09 07:43
oh.. I just tested `ghp-import `on a different repo and it works there. So there seems to be an issue with the [specific repo](https://github.com/wieselundco/website/) I'm working on. Can you give me a clue on how to debug this?

**Comment by JudgeGregg** [comment] 2021-09-03 21:17
Hello, I've just had the very same issue. Cleaning up the output directory and regenerating content solved it. I suspect I had some manually edited file which led to git crashing during file-import.

Displaying the name of files being processed in run import with:
```py
        for fn in fnames:
            print("fn: ", fn)
            fpath = os.path.join(path, fn)
```
showed:
```txt
fn:  twisted-development-policy.html                                                                                                                                                                                 
fn:  conch-howto                                                                                                                                                                                                     
                                                                                                                                                                                                                     
hidden                                                                                                                                                                                                               
                                                                                                                                                                                                                     
                                                                                                                                                                                                                     
                                                                                                                                                                                                                     
conch_client.html                                                                                                                                                                                                    
fn:  developer-guides-pair.html                                                                                                                                                                                      
fn:  working-from-twisteds-code-repository.html                                                                                                                                                                      
fn:  twisted-mail-smtp-pop-and-imap.html                                                                                                                                                                             
fn:  scheduling-tasks-for-the-future.html                                                                                                                                                                            
fn:  writing-a-twistd-plugin.html                                                                                                                                                                                    
fatal: Expected 'data n' command, found:                                                                                                                                                                             
fast-import: dumping crash report to .git/fast_import_crash_734242 
```

And the conch-howto file was indeed a file I had tinkered with. I don't know if that is the precise reason for the crash, but it did work in the end.

Thanks for your work on ghp-import :)

**Comment by c-w** [comment] 2021-09-06 20:36
Thanks for the report @JudgeGregg. @ratnanil does this information help you? Unfortunately I don't have the bandwidth to look into this right now, but a PR would be very much appreciated if you do trace this down!

**Comment by JudgeGregg** [comment] 2021-09-10 14:38
I think I can reproduce this, and it's probably not ghp-import's fault:
it happens when a filename has a line break in its name:

if you run:
```
#!/bin/zsh
touch a
cp a $'b\nc'
```
in your output directory, you will create a file with a line break in its name and git-import will fail.

Now the question is: how does pelican creates such weird filenames. I'm fairly sure it's due to some weird spacing in a rst file, but cannot reproduce it yet.

**Comment by c-w** [comment] 2021-09-26 00:53
Thanks for the investigation @JudgeGregg. Closing this at it appears to be an upstream dependency's issue. Feel free to reopen if you discover something that ghp-import could be doing better.

**Closed by c-w** 2021-09-26 00:53 UTC
