### ISSUE TITLE
use with Circle-CI

### ISSUE THREAD

**Issue by casperdcl** [c-w/ghp-import#77] opened 2019-10-28 22:34 UTC
Deploying from Circle-CI seems to work only when using https rather than ssh.

For example, this commit https://github.com/openworm/openworm_docs/commit/00f498cd7e1f2f9a3a500132500242e5829ef185 breaks deployment despite having a GitHub ssh user key with read/write access (https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys) and no default (read only) deploy key

From https://github.com/mkdocs/mkdocs/issues/1898 this appears to be a `ghp-import` issue rather than `mkdocs`.

The error message also must be wrong:

from https://circleci.com/gh/openworm/openworm_docs/598:
```bash
git fetch origin gh-pages:gh-pages
ghp-import site
git push origin gh-pages
```
produces:
```
 * [new branch]      gh-pages   -> gh-pages
ERROR: Permission to openworm/openworm_docs.git denied to openworm-bot.
fatal: Could not read from remote repository.
```
so clearly the fetch works, implying "Could not read from remote repository" should at least be "Could not write to remote repository"

**Comment by waylan** [comment] 2019-10-29 15:34
I'm assuming the problem is not with ghp-import at all as the error occurs on the last line, which is a standard git command and not part of `ghp-import`. This suggests to me that the problem is either with your config or Circle-CI. I suspect that if you can get a `git push` command to work, them all of your problems will be resolved.

**Comment by martinm82** [comment] 2020-01-03 12:05
@casperdcl, did you find any solution for your problem? We have a similar issue in our setup when running a build on Jenkins within a Docker container agent. The problem is that within the container we have not a proper environment with all the things that git requires. 

Git requires a user that has an entry in `/etc/passwd`: Therefore we mounted the host passwd to the container but fail because the home directory entry in the passwd file points to a different directory than we actually use inside the container. Changing HOME env to another directory does not help either.

So if you have some idea how to solve that please share with us

**Comment by casperdcl** [comment] 2020-01-03 17:09
The only way I could find is using https with api tokens rather than ssh.

**Comment by c-w** [comment] 2020-08-08 15:37
In https://github.com/c-w/ghp-import/pull/86 I added [integration tests](https://app.circleci.com/pipelines/github/c-w/ghp-import?branch=master) that target CircleCI. The tests are configured with a [CircleCI user key](https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys) which seems to work fine to push to Github using `ghp-import`. As such I'm resolving this issue since it seems to be related to the specific setup of the environment of @casperdcl as opposed to the integration of `ghp-import` with CircleCI. Please feel free to re-open if you're still seeing issues with `ghp-import` running on CircleCI.

**Closed by c-w** 2020-08-08 15:37 UTC
